
env:
    global:
      - CC_TEST_REPORTER_ID: 3b5683f29c74490e169b7d8a9432db09bd7976c31a5f3be263ba19fd80578e2c
  language: node_js
  node_js:
    - "9"
    - "8"
    - "7"
    - "6"
  install: npm install
  script:
    - npm run build